name: Cascading Merge
on:
  push:
    branches:
      - master
      - qa-main

jobs:
  cascading-merge:
    name: Cascading Merge
    runs-on: ubuntu-latest
    steps:
      - name: Merging
        uses: mheap/cascading-merge-action@v1
        with:
          branches: |
            master
            qa-main
