name: Update Test Branch

on:
  push:
    branches: [master]
    
permissions: 
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"

      - name: Update Test Branch
        run: |
          git checkout master
          git fetch origin
          git checkout qa-main
          git pull
          git merge origin/master
          git push origin qa-main



# name: Cascading Merge
# on:
#   push:
#     branches:
#       - master
#       - qa-main

# jobs:
#   cascading-merge:
#     name: Cascading Merge
#     runs-on: ubuntu-latest
#     steps:
#       - name: Merging
#         uses: mheap/cascading-merge-action@v1
#         with:
#           branches: |
#             master
#             qa-main
