name: PR label
on:
  pull_request:
    types: [opened, reopened]

jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: KyoriPowered/action-regex-match@v3
        id: regex-match
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '\d{2,4}\.\d{1,2}\.\d{1,2}'

      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.regex-match.outputs.match }}



#     - name: Label PRs
#       if: github.event.action == 'opened'
#       uses: ffittschen/pr-branch-labeler@v1
#       with:
#         repo-token: ${{ secrets.GITHUB_TOKEN }}
